import keyMirror from 'keymirror';

export default keyMirror({
  RECIEVE_SOURCE: null,
  RECIEVE_SOURCES: null,
  RECIEVE_TOP_SOURCE: null,
  FAV_NEWS: null,
  RECIEVE_LATEST_SOURCE: null,
  RECIEVE_POPULAR_SOURCE: null,
  RECIEVE_SOURCE_ERROR: null,
  RECIEVE_TOP_SOURCE_ERROR: null,
  RECIEVE_LATEST_SOURCE_ERROR: null,
  RECIEVE_POPULAR_SOURCE_ERROR: null,
  RECIEVE_SOURCES_ERROR: null,
});